import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState, useEffect } from 'react';
import { Alert, Button, Form } from 'react-bootstrap'
import { signIn } from '../public/services/auth.services'
import styles from '../styles/Home.module.scss'
import userStore from '../public/stores/user';
import Link from 'next/link';
import { useRouter } from 'next/router';

const Home: NextPage = () => {

  const { login, accessToken } = userStore((state) => state)
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [error, setError] = useState('')
  const router = useRouter();

  useEffect(() => {
    if(accessToken) {
      router.push('./add-friends');
    }
  }, []);

  const onSubmit = async () => {
    if (!username) { setError('Please enter username!'); return; }
    if (!password) { setError('Please enter password!'); return; }

    const obj = { username, password };
    console.log(obj)
    setError('');

    const data = await signIn(obj);
    login(data)
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Form>
          <Form.Group className="mb-3" controlId="formBasicEmail">
            <Form.Label>username</Form.Label>
            <Form.Control type="text" onChange={(e) => setUsername(e.target.value)} />
          </Form.Group>

          <Form.Group className="mb-3" controlId="formBasicPassword">
            <Form.Label>Password</Form.Label>
            <Form.Control type="password" placeholder="Password" onChange={(e) => setPassword(e.target.value)} />
          </Form.Group>
          {error && <Alert variant="danger" >{error}</Alert>}
          <Button variant="primary" className='me-2' onClick={onSubmit}>
            Login
          </Button>
          <Link href="/sign-up">
            <a href="/sign-up">{'Registor'}</a>
          </Link>
        </Form>
      </main>
    </div>
  )
}

export default Home
